Repository linz/nz-buildings, pull requests merged in 2019-05, with the labels that each got.

#267 UNIQUE update
  CHANGELOG.rst
  db/docs/source/conf.py
Labels: pr: changes approved

#259 Data Dict updates
  db/docs/source/_static/2019_coverage_map.png
  db/docs/source/_static/April_2019_coverage_map.png
  db/docs/source/_static/examples.png
  db/docs/source/introduction.rst
  db/docs/source/published_data.rst
Labels: pr: changes approved, pr: no changelog

#266 Metadata updates
  CHANGELOG.rst
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_full_history.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: changes approved

#268 Adjust published datasets based on user feedback
  CHANGELOG.rst
  README.rst
  db/docs/source/introduction.rst
  db/scripts/nz-buildings-load.in
  db/sql/buildings_common/01-create-schema-and-tables.sql
  db/sql/buildings_lds/01-create-schema-and-tables.sql
  db/sql/buildings_lds/functions/02-nz_building_outlines_all_sources.sql
  db/sql/buildings_lds/functions/05-populate_buildings_lds.sql
  db/tests/buildings_lds_populate.pg
  db/tests/testdata/10-create_test_aerial_schema.sql
  install.py
  makefile
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: changes approved

#270 Image_update
  db/docs/source/_static/examples.png
  db/docs/source/introduction.rst
Labels: pr: changes approved, pr: no changelog

#271 Metadata
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: no changelog, pr: not closing issue, pr: review requested

#278 Warning messages on adding buildings
  CHANGELOG.rst
  buildings/gui/bulk_load_changes.py
  buildings/gui/production_changes.py
Labels: pr: changes approved

#285 Updated Data Dictionary
  CHANGELOG.rst
  db/docs/source/introduction.rst
  db/docs/source/published_data.rst
Labels: pr: changes approved

#283 Editing Toolbar and Dialog- Bulk Load
  CHANGELOG.rst
  buildings/gui/bulk_load.ui
  buildings/gui/bulk_load_changes.py
  buildings/gui/bulk_load_frame.py
  buildings/gui/edit_dialog.py
  buildings/gui/edit_dialog.ui
  buildings/icons/edit_attributes.png
  buildings/icons/edit_geometry.png
  buildings/icons/minus.png
  buildings/tests/gui/test_processes_add_bulk_load.py
  buildings/tests/gui/test_processes_edit_attribute_bulk_load.py
  buildings/tests/gui/test_processes_edit_geometry_bulk_load.py
  buildings/tests/gui/test_setup_add_bulk_outline.py
  buildings/tests/gui/test_setup_edit_attribute_bulk_load.py
  buildings/tests/gui/test_setup_edit_geometry_bulk_load.py
Labels: pr: not closing issue, pr: review requested

#286 Editing Toolbar and Dialog Alter Relationships
  CHANGELOG.rst
  buildings/gui/alter_building_relationships.py
  buildings/gui/bulk_load.ui
  buildings/gui/bulk_load_changes.py
  buildings/gui/bulk_load_frame.py
  buildings/gui/edit_dialog.py
  buildings/styles/buildings_bulk_load_alter_rel.qml
  buildings/tests/gui/test_setup_alter_building_relationships.py
  buildings/utilities/circle_tool.py
Labels: pr: changes approved

#287 Editing Toolbar and Dialog- Production
  CHANGELOG.rst
  buildings/gui/bulk_load_frame.py
  buildings/gui/edit_dialog.py
  buildings/gui/edit_dialog.ui
  buildings/gui/production_changes.py
  buildings/gui/production_edits.ui
  buildings/gui/production_frame.py
  buildings/tests/gui/test_processes_add_production.py
  buildings/tests/gui/test_processes_edit_attribute_production.py
  buildings/tests/gui/test_processes_edit_geometry_production.py
  buildings/tests/gui/test_setup_add_bulk_outline.py
  buildings/tests/gui/test_setup_add_production.py
  buildings/tests/gui/test_setup_edit_attribute_bulk_load.py
  buildings/tests/gui/test_setup_edit_attribute_production.py
  buildings/tests/gui/test_setup_edit_geometry_bulk_load.py
  buildings/tests/gui/test_setup_edit_geometry_production.py
  buildings/utilities/circle_tool.py
Labels: pr: changes approved

#294 Edit dialog updates QA layer
  CHANGELOG.rst
  buildings/gui/bulk_load_changes.py
  buildings/gui/edit_dialog.py
Labels: pr: changes approved

#295 Split features while editing- Bulk Load
  CHANGELOG.rst
  buildings/gui/bulk_load_changes.py
  buildings/gui/bulk_load_frame.py
  buildings/gui/edit_dialog.py
  buildings/gui/production_changes.py
  buildings/tests/gui/test_processes_edit_geometry_bulk_load.py
Labels: pr: changes approved

#296 Fix the bug when reverting changes during add outlines
  CHANGELOG.rst
  buildings/gui/bulk_load_changes.py
  buildings/gui/edit_dialog.py
  buildings/gui/production_changes.py
  buildings/tests/gui/test_processes_add_bulk_load.py
  buildings/tests/gui/test_processes_add_production.py
Labels: pr: changes approved
