Repository linz/nz-buildings, pull requests merged in 2019-06, with the labels that each got.

#303 Pull out LIQA functionality from buildings plugin
  CHANGELOG.rst
  buildings/gui/edit_dialog.py
Labels: pr: changes approved, pr: not closing issue

#298 update the management of the buildings db test data
  CHANGELOG.rst
  db/scripts/dump_db_schema.sh
  db/scripts/nz-buildings-load.in
  db/tests/buildings_lds_populate.pg
  db/tests/testdata/02-insert_test_data_buildings_bulk_load.sql
  db/tests/testdata/03-insert_test_data_second_dataset.sql
  db/tests/testdata/04-insert_test_data_functions.sql
  db/tests/testdata/05-insert_test_data_complex.sql
  db/tests/testdata/08-insert_test_data_related_checks.sql
  db/tests/testdata/09-create_test_admin_bdys_schema.sql
  db/tests/testdata/create_test_admin_bdys_schema.sql
  db/tests/testdata/create_test_aerial_schema.sql
  db/tests/testdata/db/admin_bdys.sql
  db/tests/testdata/db/aerial_lds.sql
  db/tests/testdata/db/buildings.sql
  db/tests/testdata/db/buildings_bulk_load.sql
  db/tests/testdata/db/buildings_common.sql
  db/tests/testdata/db/buildings_lds.sql
  db/tests/testdata/db/buildings_reference.sql
  db/tests/testdata/insert_test_data_publish_lds.sql
  db/tests/testdata/plugin/admin_bdys.sql
  db/tests/testdata/plugin/aerial_lds.sql
  db/tests/testdata/update_sequences_pgtap_db.sql
  install.py
  makefile
Labels: pr: changes approved

#308 Fix sequence verify statements so that they actually verify sequences
  db/sql/verify/buildings/schema_and_tables.sql
  db/sql/verify/buildings_bulk_load/schema_and_tables.sql
  db/sql/verify/buildings_common/schema_and_tables.sql
  db/sql/verify/buildings_reference/schema_and_tables.sql
Labels: pr: changes approved, pr: no changelog

#318 Add huts to ref schema
  CHANGELOG.rst
  buildings/gui/reference_data.py
  buildings/gui/reference_data.ui
  buildings/reference_data/topo50.py
  buildings/sql/buildings_reference_select_statements.py
  db/sql/deploy/buildings_reference/functions/bivouac_points.sql
  db/sql/deploy/buildings_reference/functions/hut_points.sql
  db/sql/deploy/buildings_reference/functions/protected_area_polygons.sql
  db/sql/deploy/buildings_reference/functions/shelter_points.sql
  db/sql/deploy/buildings_reference/huts_and_protected_areas.sql
  db/sql/deploy/buildings_reference/schema_and_tables.sql
  db/sql/revert/buildings_reference/functions/bivouac_points.sql
  db/sql/revert/buildings_reference/functions/hut_points.sql
  db/sql/revert/buildings_reference/functions/protected_area_polygons.sql
  db/sql/revert/buildings_reference/functions/shelter_points.sql
  db/sql/revert/buildings_reference/huts_and_protected_areas.sql
  db/sql/sqitch.plan
  db/sql/verify/buildings_reference/functions/bivouac_points.sql
  db/sql/verify/buildings_reference/functions/hut_points.sql
  db/sql/verify/buildings_reference/functions/protected_area_polygons.sql
  db/sql/verify/buildings_reference/functions/shelter_points.sql
  db/sql/verify/buildings_reference/huts_and_protected_areas.sql
  db/tests/buildings_reference.pg
  install.py
Labels: pr: changes approved
