Repository linz/nz-buildings, pull requests merged in 2020-07, with the labels that each got.

#431 docs: updated metadata
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
Labels: pr: changes approved, pr: no changelog, pr: not closing issue

#437 Update metadata for Nelson 2019 building outlines release
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: no changelog, pr: not closing issue, pr: review requested

#436 Update data dictionary for Tasman and Nelson 2019 building outlines updates
  CHANGELOG.rst
  db/docs/source/_static/coverage_map_current.png
  db/docs/source/_static/coverage_map_future.png
  db/docs/source/conf.py
  db/docs/source/introduction.rst
Labels: pr: changes requested, pr: not closing issue, pr: review requested
