Repository linz/nz-buildings, pull requests merged in 2020-02, with the labels that each got.

#374 Optimise Localities - Use the difference between old and new suburbs
  CHANGELOG.rst
  buildings/gui/reference_data.py
  buildings/tests/gui/test_processes_update_reference_data_admin_bdys.py
  db/scripts/nz-buildings-load.in
  db/sql/deploy/buildings_reference/functions/suburb_locality_optimised.sql
  db/sql/revert/buildings_reference/functions/suburb_locality_optimised.sql
  db/sql/sqitch.plan
  db/sql/verify/buildings_reference/functions/suburb_locality_optimised.sql
  db/tests/testdata/plugin/admin_bdys.sql
  install.py
Labels: pr: changes approved

#383 Apply nz_imagery_survey_index name change to the correct files
  .github/workflows/build.yml
  CHANGELOG.rst
  db/sql/deploy/buildings_lds/functions/populate_buildings_lds.sql
  db/sql/deploy/buildings_lds/functions/populate_buildings_lds@v3.0.0-dev1.sql
  db/sql/deploy/buildings_lds/functions/populate_buildings_lds@v3.1.0-dev1.sql
  db/sql/verify/buildings_lds/functions/populate_buildings_lds@v3.1.0-dev1.sql
  db/tests/testdata/create_test_aerial_schema.sql
  db/tests/testdata/db/aerial_lds.sql
  db/tests/testdata/plugin/aerial_lds.sql
Labels: pr: changes approved, pr: not closing issue

#378 Add docs (data dictionary) for locality
  CHANGELOG.rst
  db/docs/source/_static/locality_larger_area.png
  db/docs/source/_static/locality_nearest.png
  db/docs/source/introduction.rst
  requirements-dev.txt
Labels: pr: changes approved

#385 docs: updated metadata
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
Labels: pr: no changelog, pr: not closing issue, pr: review requested
