Repository linz/nz-buildings, pull requests merged in 2020-01, with the labels that each got.

#351 Add pre-commit to lint git commit messages to match conventional commits spec
  .gitlint
  .pre-commit-config.yaml
  .travis.yml
  CHANGELOG.rst
  README.rst
  requirements-dev.txt
Labels: pr: changes approved, pr: not closing issue

#353 docs: update metadata for Bay of Plenty
  CHANGELOG.rst
  db/docs/source/_static/2020_jan_coverage_map.png
  db/docs/source/_static/2020_jan_coverage_map_future.png
  db/docs/source/introduction.rst
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: changes approved, pr: not closing issue

#352 fix: update aerial_lds.nz_imagery_surveys table name
  db/sql/deploy/buildings_lds/functions/populate_buildings_lds@v3.0.0-dev1.sql
Labels: pr: changes approved, pr: no changelog, pr: not closing issue

#355 Vertex Editing Bug in Alter Relationships and Bulk Load
  CHANGELOG.rst
  buildings/gui/alter_building_relationships.py
  buildings/gui/bulk_load_changes.py
  buildings/gui/bulk_load_frame.py
Labels: pr: changes approved

#359 build: update changelog
  CHANGELOG.rst
Labels: pr: changes approved, pr: not closing issue

#366 Optimize localities - filter by type
  CHANGELOG.rst
  buildings/tests/gui/test_processes_update_reference_data_admin_bdys.py
  db/sql/deploy/buildings_reference/functions/suburb_locality.sql
  db/tests/testdata/plugin/admin_bdys.sql
Labels: pr: changes approved

#362 ci: replace Travis-CI with GitHub Actions
  .github/workflows/build.yml
  .travis.yml
  CHANGELOG.rst
  README.rst
  buildings/tests/gui/test_processes_add_production.py
  buildings/tests/pg_config_test.ini
  db/tests/testdata/update_sequences_plugin_travis.sql
  docker-compose.yml
  install.py
  requirements-dev.txt
  testrunner.sh
Labels: pr: changes approved

#369 Update data dictionary and metadata for Gisborne building outlines release
  CHANGELOG.rst
  db/docs/source/_static/2020_jan_coverage_map.png
  db/docs/source/_static/2020_jan_coverage_map_future.png
  db/docs/source/_static/coverage_map_current.png
  db/docs/source/_static/coverage_map_future.png
  db/docs/source/introduction.rst
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: changes approved, pr: not closing issue

#377 Add new README header, update badges and versions
  CHANGELOG.rst
  README.rst
  media/header.png
Labels: pr: changes approved, pr: not closing issue
