Repository linz/nz-buildings, pull requests merged in 2020-03, with the labels that each got.

#356 Remove small tanks
  CHANGELOG.rst
  buildings/gui/bulk_load.py
  buildings/tests/gui/test_processes_bulk_load_outlines.py
  buildings/tests/testdata/test_bulk_load_shapefile.dbf
  buildings/tests/testdata/test_bulk_load_shapefile.shp
  buildings/tests/testdata/test_bulk_load_shapefile.shx
  db/sql/deploy/buildings_bulk_load/functions/remove_small_tanks.sql
  db/sql/revert/buildings_bulk_load/functions/remove_small_tanks.sql
  db/sql/sqitch.plan
  db/sql/verify/buildings_bulk_load/functions/remove_small_tanks.sql
  install.py
Labels: pr: changes approved

#388 release(3.2.0): update changelog and sqitch tag
  .gitlint
  CHANGELOG.rst
  db/sql/sqitch.plan
Labels: pr: not closing issue, pr: review requested

#397 Github Actions to run on Pull Request
  .github/workflows/build.yml
  CHANGELOG.rst
Labels: pr: changes approved, pr: not closing issue
