Repository linz/nz-buildings, pull requests merged in 2020-08, with the labels that each got.

#443 Update metadata for Otago 2020 building outlines release
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
  metadata/nz_building_outlines_lifecycle.xml
Labels: pr: changes approved, pr: no changelog, pr: not closing issue

#444 docs: updated Data Dictionary coverage images
  CHANGELOG.rst
  db/docs/source/_static/coverage_map_current.png
  db/docs/source/_static/coverage_map_future.png
Labels: pr: no reviewer, pr: not closing issue

#450 fix: update DD with Dunedin coverage
  CHANGELOG.rst
  db/docs/source/_static/coverage_map_current.png
  db/docs/source/introduction.rst
Labels: pr: changes approved, pr: not closing issue
