Repository linz/nz-buildings, pull requests merged in 2021-06, with the labels that each got.

#521 D dupdate
  db/docs/source/_static/coverage_map_current.png
  db/docs/source/_static/locality_larger_area.png
  db/docs/source/_static/locality_nearest.png
  db/docs/source/_static/logo.png
  db/docs/source/_static/logo_old.png
  db/docs/source/_static/name_use.png
  db/docs/source/conf.py
  db/docs/source/introduction.rst
Labels: pr: no changelog, pr: no reviewer, pr: not closing issue

#522 Hospitals and schools
  metadata/nz_building_outlines.xml
  metadata/nz_building_outlines_all_sources.xml
Labels: pr: changes approved, pr: no changelog, pr: not closing issue

#524 Dialog warning
  CHANGELOG.rst
  buildings/gui/bulk_load_changes.py
  buildings/gui/edit_dialog.py
  buildings/gui/edit_dialog.ui
  buildings/tests/gui/test_processes_edit_attribute_bulk_load.py
  buildings/tests/test_utilities.py
Labels: pr: changes approved
